export default  {
	GET_POSTS: 'GET_POSTS',
	GET_POST: 'GET_POST',
	GET_COMMENTS: 'GET_COMMENTS',
	GET_USERS: 'GET_USERS',
	GET_ERRORS: 'GET_ERRORS',
	SET_POST_VIEW: 'SET_POST_VIEW',
	START_LOAD: '_START_LOAD',
	FINISH_LOAD: '_FINISH_LOAD',
};
